baseURL = "https://iochen.com/"
languageCode = "en-us"
title = "Richard Chen's Blog"
theme = "iotheme"
copyright = "©2020 Richard Chen."

[params]
logo = "images/logo.svg"
style = "light"
#cdn = "https://cdn.jsdelivr.net/gh/iochen/blog-hugo@public" # FOR_CDN
comments = true

[params.nav]
showCategories = true
showTags = true

[[params.nav.custom]]
title = "About"
url = "/about/"

[[params.nav.custom]]
title = "Links"
url = "/links/"

[[params.nav.custom]]
title = "Search"
url = "/search/"

[params.license]
enable = true
author = "Richard Chen"
article = "ff"
code = "dd"

[markup]
  [markup.highlight]
    codeFences = false
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = false
    tabWidth = 4
