baseURL = "https://iochen.com/"
languageCode = "zh-CN"
title = "Richard Chen's Blog"
theme = "iotheme"
copyright = "©2020-2021 Richard Chen."

[params]
logo = "images/logo.svg"
style = "light"
#cdn = "https://cdn.jsdelivr.net/gh/iochen/blog-hugo@public" # FOR_CDN
comments = true
keywords = ["iochen","RichardChen","blog","tech","博客","技术","网络","算法","伺服器","演算法"]
description = "Richard Chen's Blog - 又一个技术博客"


[params.nav]
showCategories = true
showTags = true

[[params.nav.custom]]
title = "About"
url = "/about/"

[[params.nav.custom]]
title = "Contact"
url = "/contact/"

[[params.nav.custom]]
title = "Links"
url = "/links/"

[[params.nav.custom]]
title = "Search"
url = "/search/"


[params.license]
enable = true
author = "Richard Chen"
article = "CC BY-SA 4.0"
code = "MIT"

[markup]
  [markup.highlight]
    codeFences = false
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = false
    tabWidth = 4
  [markup.goldmark.renderer]
	unsafe = true

